#!/bin/sh

RECDIR="$1"
FPS="$2"
OUTFILE="$3"
CODEC="$4"

if [ -z "$RECDIR" ] || [ -z "$FPS" ]; then
    echo "Usage: $0 <record dir> <pics per second> [output file path] [ffmpeg codec]"
    exit 1
fi

if [ -z "$OUTFILE" ]; then
    OUTFILE="./all$FPS.mp4"
fi

if [ -z "$CODEC" ]; then
    CODEC="libx264"
fi

"$(dirname $0)"/allpicsbydate "$RECDIR" | xargs cat | ffmpeg -f image2pipe -r "$FPS" -vcodec mjpeg -i - -vcodec "$CODEC" "$OUTFILE"
