#!/bin/sh

(find . -maxdepth 1 -type d -not -name '*.git' -not -name '.') \
    | while read -r DIR; do
	for N in $(find "$DIR" -name '*.jpg' | sed 's_.*\/\([[:digit:]]\+\)\.jpg_\1_' | sort --numeric-sort;); do
	    echo $DIR/$N.jpg;
	done;
    done;
