#!/bin/sh

MIRRORDIR="$1"

print_usage()
{
    echo "Usage: $(basename "$0") <mirror directory>"
}

if [ -z "$MIRRORDIR" ]; then
    print_usage
    exit 1
fi

if ! [ -d "$MIRRORDIR" ]; then
    echo "$MIRRORDIR does not exist or is not a directory"
    exit 2
fi

if ! [ -w "$MIRRORDIR" ]; then
    echo "Cannot write in $MIRRORDIR"
    exit 3
fi

echo "------------"
if ! [ -f out24.mp4 ]; then
    echo "PROCESS"
    $(dirname $0)/skeleton/all24
    if ! [ -f out24.mp4 ]; then
	exit 1
    fi
fi


echo "------------"
DESTDIR="$MIRRORDIR/$(pwd | sed 's_/.*/\([^/]\+\)$_\1_')/"
if ! [ -d "$DESTDIR" ]; then
    echo "CREATING WEB DIR"
    mkdir "$DESTDIR"
    if ! [ -d "$DESTDIR" ]; then
	exit 2
    fi
fi


echo "------------"
if ! [ -f "$DESTDIR/out24.mp4" ]; then
    echo "LINK FROM DESTDIR TO VIDEO FILE"
    ln -s `pwd`/out24.mp4 "$DESTDIR/out24.mp4"
    if ! [ -f "$DESTDIR/out24.mp4" ]; then
	exit 3
    fi
fi


echo "------------"
if [ -h "$MIRRORDIR/last_dir" ]; then
    rm "$MIRRORDIR/last_dir"
fi
echo "LINK DIR"
ln -s "$DESTDIR" "$MIRRORDIR/last_dir"


echo "------------"
if [ -h "$MIRRORDIR/last.mp4" ]; then
    rm "$MIRRORDIR/last.mp4"
fi
echo "LINK FILE"
ln -s "$DESTDIR/out24.mp4" "$MIRRORDIR/last.mp4"
