#!/bin/sh

DIR="$1"

if [ -z "$DIR" ]; then
    # DIR="."
    echo "Usage: $0 RECDIR"
    exit 1
fi

if [ -h "$DIR/last_dir" ]; then
    if ! rm "$DIR/last_dir"; then
	exit 1
    fi
fi

ln -s $($(dirname $0)/lastrecdir "$DIR") "$DIR/last_dir"
