#!/bin/sh

DEV="$1"
SECS="$2"

print_usage()
{
    echo "Usage: $(basename "$0") <device> <span_in_seconds>"
}

if [ -z "$DEV" ] || [ -z "$SECS" ]; then
    print_usage
    exit 1
fi

if ! [ -e "$DEV" ]; then
    echo "Device \"$DEV\" does not exist"
    exit 2
fi

if ! echo $SECS | grep '^[^0][[:digit:]]*$'; then
    echo "Bad time format. For example, if you want to snap every minute, just type 60 as first parameter"
    exit 3
fi

export DIR=rec_`date --rfc-3339=seconds | sed 's/ /_/'`

mkdir "$DIR"

echo -n 0 > i

watch -p -n $SECS 'FILE="$DIR/`cat i`.jpg" && ./snap '"$DEV"' "$FILE"&& I=`cat i` && I=`echo "$I+1" | bc` && echo -n $I > i'
