#!/bin/bash

export DIR=rec_`date --rfc-3339=seconds | sed 's/ /_/'`

mkdir "$DIR"

echo -n 0 > i

watch -p -n 60 'FILE="$DIR/`cat i`.jpg" && ./snap "$FILE" && I=`cat i` && I=`echo "$I+1" | bc` && echo -n $I > i'
