#!/bin/sh

DEV="$1"
OUTFILE="$2"
FILTER="$3"

print_usage()
{
    echo "Usage: $0 <device> <output file> [ffmpeg filter]"
}

if ! [ -e "$DEV" ]; then
    echo "Device \"$DEV\" does not exist"
    print_usage
    exit 1
fi

if [ -z "$OUTFILE" ]; then
    print_usage
    exit 2
fi

ffmpeg -y -loglevel error -i "$DEV" $(if ! [ -z "$FILTER" ]; then echo "-vf" "$FILTER"; fi) -vframes 1 "$OUTFILE"
