#!/bin/sh

RECDIR="$1"
ARCHNAME="$2"

if [ -z "$RECDIR" ] || [ -z "$ARCHNAME" ]; then
    echo "Usage: $0 <record dir> <desired archive name>"
    exit 1
fi

tar --gzip --verbose --create --file "$ARCHNAME" $($(dirname "$0")/alldirsbydate "$RECDIR")
