#!/bin/sh

ARCHNAME="$1"

if [ -z "$ARCHNAME" ]; then
    echo "Usage: $0 <desired archive name> [record dir]"
    exit 1
fi

RECDIR="$2"

if [ -z "$RECDIR" ]; then
    RECDIR="."
fi

tar --gzip --verbose --create --file "$ARCHNAME" $($(dirname "$0")/alldirsbydate "$RECDIR")
