#!/bin/sh

$(dirname $0)/files > list

PICS=$(cat list)

if [ -z "$PICS" ]; then
    echo "No pics to process"
    rm -f list
    exit 1
fi

rm list

cat $PICS | ffmpeg -f image2pipe -r 24 -vcodec mjpeg -i - -vcodec libx264 out24.mp4
